name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make clean && make
    - name: make debug
      run: make clean && make DEBUG=1
    - name: make gdb
      run: make clean && make GDB=1
    - name: make cli
      run: make clean && make CLI=1
    - name: make diff
      run: make clean && make DIFF=1
